### ISSUE TITLE
Max Flow Macro dont start

### ISSUE THREAD

**Issue by Fragmon** [fbeauKmi/V2.3934#24]
Hey i try to test your max flow macro. I get the problems that after start the temp settings will override to 0/0.

**Comment by Fragmon** [comment]
I think its this call that stopps the macro:

    {% if printer.extruder.can_extrude %}

**Comment by fbeauKmi** [comment]
Hi, Thanks for this one, i'll take a look at that. It is possible that my DB_Filamaent macro interfere. How did you call the macro ? Was your printer heating up ?
I use `{% if printer.extruder.can_extrude %} ` to prevent extrusion if printer is not ready

**Comment by Fragmon** [comment]
I use the main calibrate and the max macro directly. It shows the correct response but then it stops and set extruder and bed to 0

**Comment by fbeauKmi** [comment]
It looks like you directly enter print_end. Was your extruder reach the `min_extrude_temp` set in your `[extruder]` section

**Comment by Fragmon** [comment]
min temp = 0
